// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Vercel Postgres 常见变量名做回退；本地推荐统一写成 DATABASE_URL
    url:
      process.env["DATABASE_URL"] ??
      process.env["POSTGRES_PRISMA_URL"] ??
      process.env["POSTGRES_URL"],
  },
});
